# Site settings
title: Rosa Ekström
email: rjosih@hotmail.com
description: Copyright © 2016 Rosa Ekström
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rosaekstrom
github_username: re222gr

# Build settings
markdown: kramdown
